
name: update-dev
on:
  push:
    branches:
      - development-main

# env:
  # FIRST_NAME: Mona
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git pull on CLS (DEV)
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /var/www/dev.myswimmingclub.uk/software/
            git pull
          host: ${{ secrets.HOST_SCDS }}
          user: ${{ secrets.USER_SCDS }}
          key: ${{ secrets.USER_PRIVATE_KEY_SCDS}}
          # pass: ${{ secrets.PASS_SCDS }}