
name: update
on:
  push:
    branches:
      - main

# env:
  # FIRST_NAME: Mona
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git pull on SCDS Managed Hosting
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /var/www/membership-mt/php/production/
            git pull
            composer install
            curl "https://membership.myswimmingclub.uk/db/run"
            npm install
            npm run build-production
          host: ${{ secrets.HOST_SCDS }}
          user: ${{ secrets.USER_SCDS }}
          key: ${{ secrets.USER_PRIVATE_KEY_SCDS}}
          # pass: ${{ secrets.PASS_SCDS }}
